### ISSUE TITLE
Cannot invoke 'moveAlong' with an argument list of type '(points: [SCNVector3], duration: Int, fps: Int)'

### ISSUE THREAD

**Issue by abbana** [maxxfrazer/SceneKit-Bezier-Animations#1]
Cannot invoke 'moveAlong' with an argument list of type '(points: [SCNVector3], duration: Int, fps: Int)'

**Comment by abbana** [comment]
Just followed the readme, got that.

**Comment by maxxfrazer** [comment]
Is this all good now @abbana ? Please close the issue if it’s no longer relevant

Also once you’re done I’d love to see what you create!

**Comment by abbana** [comment]
Hi Max,

not really. Following the instructions provided I got that error. Just quick look on the functions I can’t see that initialiser. Swift on Xcode 10

**Comment by maxxfrazer** [comment]
@abbana the function declaration requires duration: TimeInterval

All here with inline documentation:
https://github.com/maxxfrazer/SceneKit-Bezier-Animations/blob/92f9604cbdb890f648672a612ba8bf335ada7558/SCNBezier/SCNAction%2BExtensions.swift#L21

**Comment by maxxfrazer** [comment]
If that’s the problem then please let me know so I can update the issue accordingly.

**Comment by maxxfrazer** [comment]
@abbana I'll assume that this was the problem and close this issue.
