### ISSUE TITLE
Not working correctly for fast animations

### ISSUE THREAD

**Issue by nickasd** [maxxfrazer/SceneKit-Bezier-Animations#3]
Thank you for providing this framework. I noticed though that when using very fast animations, and this possibly is an issue as well when the game hangs and hence doesn't call the action's block at regular intervals, nodes do not animate correctly to their final positions. I looked quickly through the code and it seems that you precompute the points along the path, but this works only assuming that the block is called regularly. I use the following code now which proved to work correctly:
```
static func moveAlong(bezier2 bezier: [SCNVector3], duration: TimeInterval) -> SCNAction {
    if bezier.count < 3 {
        fatalError()
    }
    return SCNAction.customAction(duration: duration, action: { (node, t) in
        let t = t / SCNFloat(duration)
        node.position = bezier[1] + (1 - t) * (1 - t) * (bezier[0] - bezier[1]) + t * t * (bezier[2] - bezier[1])
    })
}
```

**Comment by maxxfrazer** [comment]
Hi @nickasd thanks for posting this! If you want to open a pull request this might be good to add to the package?

**Comment by nickasd** [comment]
You're welcome. In my own code I don't use `SCNAction` directly anymore so it's not worth for me doing a PR, but feel free to integrate if yourself if you want.
